# Generated by Django 3.1.2 on 2023-10-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20231007_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
    ]
