# Generated by Django 3.1.2 on 2023-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
