# Generated by Django 3.1.2 on 2023-10-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_place_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
