# Generated by Django 3.1.2 on 2023-10-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_training_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
