# Generated by Django 3.1.2 on 2023-10-07 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20231008_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='booking_date',
            new_name='last_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='training',
            name='coupon_used',
        ),
        migrations.RemoveField(
            model_name='training',
            name='status',
        ),
    ]
